# Generated by Django 4.0.5 on 2022-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_time',
            field=models.CharField(max_length=150),
        ),
    ]
