apiVersion: v1
kind: Service
metadata:
  name: daktari-prediction
  labels:
    app: daktari-prediction
spec:
  type: NodePort
  selector:
    app: daktari-prediction
  ports:
    - port: 8000
      targetPort: 8000
